#!/usr/bin/env python3
"""Run vulpen for long, or through many live swaps, and fail when what it holds keeps
growing (A03): memory, GPU memory, threads, open files, and the recipe modules it maps.

--minutes runs the wave example headless and unpaced, and the triangle example in a
window where a display exists, sampling both every 10 s; it writes what it saw to
docs/statistics/soak.md (RD01). --swaps needs a live build: it saves a shader, a module
and the manifest of the wave example in turn, without changing them, and samples after
each swap.

Usage: python3 src/tools/tests/soak.py VULPEN (--minutes N | --swaps N [--races-only])
  --races-only  judge what the run prints, not what it holds: a sanitizer's memory grows
"""
import argparse
import os
import queue
import re
import shutil
import subprocess
import sys
import threading
import time
from pathlib import Path

from harness import EXAMPLES, PROBLEM, ROOT, display, environment

SAMPLE_INTERVAL = 10  # seconds
WARM_UP = 0.2  # of the samples, left out while caches and pools fill
# Growth past this between the first and the last third of the samples counts as a leak.
ALLOWED = {"memory KiB": 1024, "GPU MiB": 1, "threads": 0, "files": 0, "modules": 0}
SWAP_TIMEOUT = 300  # seconds for one build and swap
WAVE = EXAMPLES / "wave"
SAVED = [WAVE / "recipes" / "wave" / "Wave.comp", WAVE / "recipes" / "wave" / "Wave.cpp",
         WAVE / "view.vlp"]
STATISTICS = ROOT / "docs" / "statistics" / "soak.md"
GENERATED = ("Generated by [`src/tools/tests/soak.py`](../../src/tools/tests/soak.py), "
             "which the nightly tests run; rerun it instead of editing this file.")


class Run:
    """One vulpen process and what it prints, read as it goes so its pipe never fills."""

    def __init__(self, vulpen: str, arguments: list, headless: bool, listen: bool = False):
        self.process = subprocess.Popen([vulpen, *map(str, arguments)], text=True,
                                        errors="replace", stdout=subprocess.PIPE,
                                        stderr=subprocess.STDOUT,
                                        env=environment(headless))
        self.listen = listen  # whether wait_for() will read the lines
        self.lines: queue.Queue[str] = queue.Queue()
        self.problems: list[str] = []
        threading.Thread(target=self.read, daemon=True).start()

    def read(self) -> None:
        for line in self.process.stdout:
            if PROBLEM.search(line) or "{!!!}" in line:
                self.problems.append(line.rstrip())
            if self.listen:
                self.lines.put(line)

    def wait_for(self, text: str, timeout: float) -> str:
        """The first line holding text or an error; fails on neither within the time."""
        end = time.monotonic() + timeout
        while (left := end - time.monotonic()) > 0:
            try:
                line = self.lines.get(timeout=left)
            except queue.Empty:
                break
            if text in line or "{!!!}" in line:
                return line
        sys.exit(f"no '{text}' within {timeout} s; vulpen said:\n" + "\n".join(self.problems))

    def sample(self) -> dict[str, int]:
        pid = self.process.pid
        status = Path(f"/proc/{pid}/status").read_text()
        field = lambda name: int(re.search(rf"^{name}:\s+(\d+)", status, re.M).group(1))
        maps = Path(f"/proc/{pid}/maps").read_text()
        values = {"memory KiB": field("VmRSS"), "threads": field("Threads"),
                  "files": len(os.listdir(f"/proc/{pid}/fd")),
                  "modules": len(set(re.findall(r"\S+/views/\S+/recipe\.so", maps)))}
        if (gpu := gpu_memory(pid)) is not None:
            values["GPU MiB"] = gpu
        return values

    def stop(self) -> None:
        if self.process.poll() is not None:
            sys.exit(f"vulpen ended early, with exit {self.process.returncode}:\n"
                     + "\n".join(self.problems))
        self.process.terminate()
        self.process.wait()


def gpu_memory(pid: int) -> int | None:
    """What an NVIDIA GPU holds for the process; lavapipe's shows as its memory."""
    if not shutil.which("nvidia-smi"):
        return None
    table = subprocess.run(["nvidia-smi"], capture_output=True, text=True).stdout
    found = re.search(rf"\b{pid}\b.*?(\d+)MiB", table)
    return int(found.group(1)) if found else None


def growth(samples: list[dict[str, int]]) -> list[str]:
    """What rose from the first third to the last, after the warm-up: the least of the
    last third above the most of the first, so one busy moment is no leak."""
    if not samples:
        return []
    settled = samples[int(len(samples) * WARM_UP):]
    third = max(1, len(settled) // 3)
    found = []
    for name, allowed in ALLOWED.items():
        if name not in settled[0]:
            continue
        first = max(sample[name] for sample in settled[:third])
        last = min(sample[name] for sample in settled[-third:])
        if last - first > allowed:
            found.append(f"{name} grew from {first} to {last}")
    return found


def soak(vulpen: str, minutes: float) -> None:
    runs = {"wave": Run(vulpen, [WAVE / "view.vlp", "--fps", 0], headless=True)}
    if display():
        runs["triangle"] = Run(vulpen, [EXAMPLES / "triangle" / "view.vlp"], headless=False)
    samples: dict[str, list[dict[str, int]]] = {name: [] for name in runs}
    end = time.monotonic() + minutes * 60
    while time.monotonic() < end:
        time.sleep(SAMPLE_INTERVAL)
        for name, one in runs.items():
            samples[name].append(one.sample())
    for one in runs.values():
        one.stop()
    write(minutes, samples)
    judge({name: (samples[name], one.problems) for name, one in runs.items()})


def swaps(vulpen: str, count: int, races_only: bool) -> None:
    one = Run(vulpen, [WAVE / "view.vlp", "--fps", 60, "--log", "info"], headless=True,
              listen=True)
    one.wait_for("live code:", SWAP_TIMEOUT)
    samples = [one.sample()]
    for index in range(count):
        os.utime(SAVED[index % len(SAVED)])  # saved, unchanged
        if "{!!!}" in one.wait_for("and swapped", SWAP_TIMEOUT):
            break
        samples.append(one.sample())
    one.stop()
    modules = {sample["modules"] for sample in samples}
    judge({"wave": ([] if races_only else samples, one.problems + (
        [f"the mapped recipe modules went from {samples[0]['modules']} to {modules}"]
        if len(modules) > 1 else []))})


def judge(results: dict[str, tuple[list[dict[str, int]], list[str]]]) -> None:
    failed = [f"{name}: {problem}" for name, (samples, problems) in results.items()
              for problem in problems + growth(samples)]
    if failed:
        sys.exit("\n".join(failed))


def write(minutes: float, samples: dict[str, list[dict[str, int]]]) -> None:
    lines = ["# Soak", "", GENERATED, "",
             f"{minutes:g} minutes, sampled every {SAMPLE_INTERVAL} s, on "
             f"{time.strftime('%Y-%m-%d')}. Each cell reads first → last sample.", "",
             "| View | " + " | ".join(ALLOWED) + " |",
             "| --- |" + " --: |" * len(ALLOWED)]
    for name, taken in samples.items():
        cells = [f"{taken[0][key]} → {taken[-1][key]}" if key in taken[0] else "–"
                 for key in ALLOWED]
        lines.append(f"| {name} | " + " | ".join(cells) + " |")
    STATISTICS.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("vulpen")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--minutes", type=float)
    mode.add_argument("--swaps", type=int)
    parser.add_argument("--races-only", action="store_true")
    options = parser.parse_args()
    if options.minutes:
        soak(options.vulpen, options.minutes)
    else:
        swaps(options.vulpen, options.swaps, options.races_only)


if __name__ == "__main__":
    main()
