#!/usr/bin/env python3
"""Fill docs/statistics/ with the line counts of this tree and the timings of its release build.

Every build runs it; a release build passes its binary, so the timings come from the
code as built. Building from here instead would nest a build inside the one running it.
The timings keep a row per system, so each OS and GPU the code runs on stays on the page.

Usage: python3 src/tools/fetch-statistics.py [--binary PATH]
"""
import argparse
import platform
import re
import statistics
import subprocess
import sys
import time
from collections import Counter
from pathlib import Path, PurePosixPath

ROOT = Path(__file__).resolve().parents[2]
STATISTICS = ROOT / "docs" / "statistics"
PRESET = "release"
RUNS = 20
MS_PER_S = 1000
KIB = 1024
GENERATED = ("Generated by [`src/tools/fetch-statistics.py`](../../src/tools/fetch-statistics.py),"
             " which every build runs; rebuild instead of editing this file.")
# It runs headless, so the warm-up names the GPU without opening a window.
HEADLESS = ROOT / "src" / "examples" / "wave" / "view.vlp"
TIMINGS = ("| System | CPU | GPU | Build | Startup to exit, median | Startup to exit, fastest "
           "| Binary size |")
SYSTEM_CELLS = 3  # a row's first cells name its system: a run there rewrites the row

# Comment markers: line comment, block comment open, block comment close.
C_STYLE = ("//", "/*", "*/")
HASH = ("#", None, None)
LANGUAGES = {  # looked up by file name first, then by suffix
    **dict.fromkeys((".cpp", ".h", ".hpp"), ("C++", C_STYLE)),
    **dict.fromkeys((".glsl", ".vert", ".tesc", ".tese", ".geom", ".frag", ".comp"),
                    ("GLSL", C_STYLE)),
    ".vlp": ("Manifest", HASH),
    ".py": ("Python", HASH),
    "CMakeLists.txt": ("CMake", HASH),
    ".cmake": ("CMake", HASH),
    ".sh": ("Shell", HASH),
    ".ps1": ("PowerShell", ("#", "<#", "#>")),
}
COLUMNS = ("files", "code", "comment", "blank")


def run(*command: str, stdin: str = "") -> str:
    """Run a command in ROOT and return its stdout; on failure, exit with its output."""
    result = subprocess.run(command, cwd=ROOT, input=stdin, capture_output=True,
                            encoding="utf-8", errors="replace")
    if result.returncode != 0:
        sys.exit(f"{' '.join(command)} exited {result.returncode}\n{result.stdout}{result.stderr}")
    return result.stdout


def save(name: str, lines: list[str]) -> None:
    path = STATISTICS / name
    temporary = path.with_name(f"{name}.tmp")
    temporary.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    temporary.replace(path)  # a killed run never leaves half a file
    print(f"wrote {path.relative_to(ROOT).as_posix()}")


def counted_files() -> list[str]:
    listed = run("git", "ls-files", "-z", "--cached", "--others", "--exclude-standard")
    paths = sorted({path for path in listed.split("\0") if path and (ROOT / path).is_file()})
    # Vendored code is not ours to count; .gitattributes marks it, and GitHub's
    # language bar reads the same mark.
    attributes = run("git", "check-attr", "-z", "--stdin", "linguist-vendored",
                     stdin="".join(f"{path}\0" for path in paths)).split("\0")
    vendored = {path for path, value in zip(attributes[::3], attributes[2::3])
                if value in ("set", "true")}
    return [path for path in paths if path not in vendored]


def string_end(line: str, start: int) -> int:
    """Index just past the string or character literal that opens at start."""
    i = start + 1
    while i < len(line) and line[i] != line[start]:
        i += 2 if line[i] == "\\" else 1
    return i + 1


def classify(text: str, markers: tuple) -> Counter:
    """Count blank, comment and code lines; a line holding any code counts as code."""
    line_comment, block_open, block_close = markers
    counts, in_block = Counter(), False
    for line in text.splitlines():
        code, i = False, 0
        while i < len(line):
            if in_block:
                end = line.find(block_close, i)
                if end < 0:
                    break
                in_block, i = False, end + len(block_close)
            elif line.startswith(line_comment, i):
                break
            elif block_open and line.startswith(block_open, i):
                in_block, i = True, i + len(block_open)
            elif line[i] in "\"'":  # skipped whole, so a /* inside a string opens no comment
                code, i = True, string_end(line, i)
            else:
                code, i = code or not line[i].isspace(), i + 1
        counts["code" if code else "comment" if line.strip() else "blank"] += 1
    return counts


def line_counts() -> tuple[dict, dict]:
    by_language, by_folder = {}, {}
    for path in map(PurePosixPath, counted_files()):
        entry = LANGUAGES.get(path.name) or LANGUAGES.get(path.suffix)
        if entry is None:
            continue
        language, markers = entry
        counts = classify((ROOT / path).read_text(encoding="utf-8", errors="replace"), markers)
        counts["files"] = 1
        by_language.setdefault(language, Counter()).update(counts)
        by_folder.setdefault(f"`{path.parent}/`", Counter()).update(counts)
    return by_language, by_folder


def table(heading: str, rows: dict) -> list[str]:
    lines = [f"| {heading} | " + " | ".join(column.title() for column in COLUMNS) + " |",
             "| --- |" + " --: |" * len(COLUMNS)]
    for name, counts in [*sorted(rows.items()), ("**Total**", sum(rows.values(), Counter()))]:
        lines.append(f"| {name} | " + " | ".join(str(counts[column]) for column in COLUMNS) + " |")
    return lines


def write_loc() -> None:
    by_language, by_folder = line_counts()
    save("LOC.md", ["# Lines of code", "",
                    f"{GENERATED} A line holding any code counts as code. Files git ignores or "
                    "`.gitattributes` marks vendored are left out.", "",
                    "## By language", "", *table("Language", by_language), "",
                    "## By folder", "", *table("Folder", by_folder)])


def timed_run(binary: Path) -> float:
    start = time.perf_counter()
    code = subprocess.call([binary], cwd=ROOT, stdout=subprocess.DEVNULL)
    seconds = time.perf_counter() - start
    if code != 0:
        sys.exit(f"{binary} exited {code}")
    return seconds


def cpu_model() -> str:
    cpuinfo = Path("/proc/cpuinfo")  # on Linux, platform.processor() names only the architecture
    if cpuinfo.exists():
        for line in cpuinfo.read_text().splitlines():
            if line.startswith("model name"):
                return line.split(":", 1)[1].strip()
    if platform.system() == "Windows":  # where it names only the family
        import winreg
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE,
                            r"HARDWARE\DESCRIPTION\System\CentralProcessor\0") as key:
            return winreg.QueryValueEx(key, "ProcessorNameString")[0].strip()
    return platform.processor() or "unknown"


def timing_rows() -> list[list[str]]:
    """The rows performance.md holds, as cells; none while it has another layout."""
    path = STATISTICS / "performance.md"
    lines = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    if TIMINGS not in lines:
        return []
    return [[cell.strip() for cell in line.strip("|").split("|")]
            for line in lines[lines.index(TIMINGS) + 2:] if line.startswith("|")]


# Peak memory is left out: a child's ru_maxrss starts at the RSS of the Python
# process that spawned it, so for a small binary it measures Python.
def write_performance(binary: Path) -> None:
    # The warm-up run; the log's first {run} line, below its header, names the commit.
    said = run(str(binary), str(HEADLESS), "--frames", "1", "--log", "info")
    build = re.search(r"\{run\} (.+)", said).group(1)
    gpu = re.search(r"\{gpu\} runs on (.+): ", said).group(1)
    times = [timed_run(binary) * MS_PER_S for _ in range(RUNS)]
    row = [platform.system(), cpu_model(), gpu, f"`{build}`",
           f"{statistics.median(times):.2f} ms", f"{min(times):.2f} ms",
           f"{binary.stat().st_size / KIB:.1f} KiB"]
    rows = [row if old[:SYSTEM_CELLS] == row[:SYSTEM_CELLS] else old for old in timing_rows()]
    if row not in rows:
        rows.append(row)
    save("performance.md", ["# Performance", "",
                            f"{GENERATED} Times run from spawn to exit, over {RUNS} runs of the "
                            f"`{PRESET}` build after one warm-up run, so they include the OS "
                            "starting a process: compare them only within one system. Each "
                            f"system, CPU and GPU keeps one row, which its next `{PRESET}` build "
                            "rewrites.", "",
                            TIMINGS, "| --- | --- | --- | --- | --: | --: | --: |",
                            *(f"| {' | '.join(cells)} |" for cells in rows)])


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--binary", type=Path, help=f"also time this {PRESET} binary")
    binary = parser.parse_args().binary
    write_loc()
    if binary:
        write_performance(binary)


if __name__ == "__main__":
    main()
